--- 
services: 
  mariadb: 
    build: req/mariadb
    container_name: mariadb
    environment: 
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    image: "mariadb:test"
    ports: 
      - "3306:3306"
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - docker_network
  nginx:
    build: req/nginx
    container_name: nginx
    depends_on: 
      - wordpress
    image: "nginx:test"
    ports: 
      - "443:443"
    restart: always
    volumes: 
      - "wordpress_data:/var/www/html"
    networks:
      - docker_network
  wordpress: 
    build: req/wordpress
    container_name: wordpress
    depends_on: 
      mariadb:
        condition: service_healthy
    environment: 
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_HOSTNAME=${DB_HOSTNAME}"
      - "WP_URL=${WP_URL}"
      - "WP_ADMIN=${WP_ADMIN}"
      - "WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}"
      - "WP_ADMIN_MAIL=${WP_ADMIN_MAIL}"
      - "WP_USER=${WP_USER}"
      - "WP_USER_PASSWORD=${WP_USER_PASSWORD}"
      - "WP_USER_MAIL=${WP_USER_MAIL}"
    image: "wordpress:latest"
    ports: 
      - "9000:9000"
    restart: always
    volumes: 
      - "wordpress_data:/var/www/html"
    networks:
      - docker_network

networks:
  docker_network:

volumes: 
  db_data: 
    #  driver: local
    driver_opts: 
       device: /home/mlebard/data/mysql
       o: bind
       type: none
  wordpress_data: 
    #   driver: local
     driver_opts: 
       device: /home/mlebard/data/wordpress
       o: bind
       type: none
version: "2.1"
