--- 
services: 
  mariadb: 
    build: req/mariadb
    container_name: mariadb
    environment: 
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    image: "mariadb:test"
    ports: 
      - "3306:3306"
    restart: always
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql 
         # - db_data:/var/lib/mysql
  nginx: 
    #build: req/nginx
    container_name: nginx
    depends_on: 
      - wordpress
    image: "nginx:latest"
    ports: 
      - "443:443"
    restart: always
    volumes: 
      - "wordpress_data:/var/www/html/wordpress"
  wordpress: 
    #build: req/wordpress
    container_name: wordpress
    depends_on: 
      - mariadb
    environment: 
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_HOSTNAME=${DB_HOSTNAME}"
    image: "wordpress:latest"
    ports: 
      - "9000:9000"
    restart: always
    volumes: 
      - "wordpress_data:/var/www/html/wordpress"
volumes: 
  db_data: 
    #  driver: local
    driver_opts: 
       device: /home/mlebard/data/mysql
       o: bind
       type: none
  wordpress_data: 
    #   driver: local
     driver_opts: 
       device: /home/mlebard/data/wordpress
       o: bind
       type: none
version: "3.8"
